### ISSUE TITLE
More hash_algorithms, like sha3 or blake2? 

### ISSUE THREAD

**Issue by yjqiang** [wbond/oscrypto#39]
https://docs.python.org/3/library/hashlib.html
Of course sha3 and blake2 are safer than sha2 and md5. But I also noticed they were added recently in python3.6, while oscrypto supports python2. So I'm not sure about whether we should support them right now.

**Comment by wbond** [comment]
oscrypto is designed to expose the underlying crypto libraries on Windows, Mac and Linux. Because of that, and the fact that OSes tend to be slow in adding “new” cryptography, this wouldn’t be a good fit.

If you are looking to use more modern crypto you’ll probably need to go down the route of obtaining wheels for the Python libraries you need and the versions of Python you support.

**Comment by yjqiang** [comment]
https://github.com/wbond/oscrypto/blob/master/oscrypto/_pkcs1.py#L250-L259
I checked the code and I think maybe we can just change these set `set(['sha1', 'sha224', 'sha256', 'sha384', 'sha512'])` and add `blake2s`, then we can easily supported new hash_algorithms. So is this doable?

**Comment by wbond** [comment]
That would only help for RSA signing/verification with PSS padding on OSes that don’t support it in their crypto lib. I don’t recall off of the top of my head, but it may only be older versions of Windows and Mac.

Such shims are minimized and only used where there are no other options. Considering blake2 isn’t support by Security.framework or CNG, I don’t have plans to add support for it. Additionally, oscrypto is design for Python 2.6+ and 3.3+. Anything that requires newer versions of Python 3 won’t be included.

It’s not that people wouldn’t find a smattering if different features useful, it is just that I have no interest in creating a fragmented library where various features on work on specific combinations of the OS and versions of Python.

For the most part, oscrypto is feature complete. Since I designed it to allow me to use some baseline crypto across operating systems without installing C modules. Since I’ve pretty much implemented everything that is broadly supported, there isn’t much left to do. The only thing I could consider would be DH key agreement.

Secondly, I don’t really have time to work on new features.

**Comment by yjqiang** [comment]
Got it, thanks a lot.
